<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends AppRepository
{

    /**
     * @param int $page
     * @param int $limit
     * @return \Pagerfanta\Pagerfanta
     */
    public function getProducts($page=1, $limit=100)
    {
        $queryBuilder = $this->createQueryBuilder('t');
        $queryBuilder->innerJoin(Category::class, 'category');

        $pager = $this->paginate($queryBuilder, $page, $limit);

        return $pager;
    }

    public function remove($entity)
    {
        $em = $this->getEntityManager();
        $em->remove($entity);
        $em->flush();
    }

    public function persist($entity)
    {
        $em = $this->getEntityManager();
        $em->persist($entity);
        $em->flush();
    }


}
