app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: api_routes.yml
    type: rest
    prefix: /api/v1

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }